# Conclusion

After an in-depth analysis of the response data on pro-environmental attitude among college students of India, this section will mark the end of this study. I will conclude the study by presenting a summary of findings and explanations. I would also provide necessary and important suggestions. One limitation that posed difficulty in analyzing the data was it's small sample size. Further research and study on this pro-environmental attitude analysis of students, in context of India is very important and is welcomed.

## Summary

We found several key fact and results from our analysis about the college students of India on their positive attitude towards the environment. These findings are summarized as follows:

-   **Overall average pro-environmental attitude score on our questionnaire is above 80% with 95% confidence**. The **students are highly concerned about the environment on an average**. Even the **distribution of pro-environmental attitude score is skewed peaking around above average score**.

-   The **average percentage attained in all domains i.e. Recycling, Environmental Safety, Perceived Control, Social Support, Environmental Reductionism, Environmental Sensitivitiy, Reuse and Environmental Conservation that constituted our pro-environmental score of an individuals, are more or less the same**.

-   Students have good knowledge and **showed similarity as expected in the domains of Environmental Reductionism and Conservation; Recycling and Reuse**.

-   The students had **confusion or lack of idea on few domains like ways to conserve natural resources, ways to upcycle old products**.

-   The students are also found to be **having difficulties in managing waste around them and recycling**.

-   Students are **less aware about seeking social support for environmental protection** and somewhat **have little belief that their individual contribution can bring about significant change in the betterment of climate and environment**.

-   Students are **highly aware of their responsibilities like closing tap, switching off fans when not in use and supports taking stricter actions and norms against environmental pollution**.

-   The **overall pro-environmental attitude of the students is constituted mainly by their attitude towards recycling, reuse, conservation and environmental reductionism** and less contribution from the other domains.

## Suggestions

After we have understood the areas of pro-environmental attitude where the students lack. I provide some important suggestions as follows:

-   Even though the overall average pro-environmental score is above, **students didn't knew much or showed less pro-environmental attitude in few domains** compared to the others and **necessary steps need to be taken to provide them with necessary knowledge and inculcate good practice** in them in those domains i.e. **Social Support, Environmental Sensitivity, Environmental Safety and Perceived Control**.

-   **Education and good practices** about **managing waste around in the surroundings** is very important and **students lacked it**.

-   Similarly, **proper information and idea about upcycling and reuse of old or waste products** needs to be inculcated among the students.

-   Students should be **motivated to believe that their individual efforts can help in slowing down climate change and can help in environmental protection**. They should also be **motivated to be socially active in seeking support** and **participating in clubs and events regarding environmental protection**.

-   There is an **immense need for proper knowledge** about the **ways to conserve natural resources** and **reduction of use of natural resources in everyday life**.

Since, this study was conducted on college students of India. There is **still further study required to capture variations all across India** with large sample size. But it is very important to understand that **if proper care and necessary stress on domains ,that the college students are unaware of, is given right from the childhood and school of a child's education**, I believe **we can see much better results in terms of their environmental awareness** and they would grow up into **responsible citizen who are concerned and work upon to protect the environment**.

# Future Study

The future of the planet is in the hands of the youth: they are the decision makers of the future. It is therefore necessary to understand what drives children and young people to behave in a pro-environmental manner. Policy makers, curriculum developers and designers of environmental education programs have expressed a keen interest in knowing how environmental attitudes develop among young people and what causes the differences in these attitudes. Young people's environmental attitudes have also become a growing topic for social scientists. Most research aimed at explaining differences in (adolescent) environmental attitudes focuses on the individual as a measurement level. However, individuals operate within a social structure; they are part of a context. People are born into and grow up in a cultural environment that influences and shapes their attitudes and behaviors (Giddens 1997). Therefore, rather than viewing the individual as just themselves, a better level of measurement would be the individual in their context. Attitudes are expressed in actions and in the interaction between people. The context and the social groups we belong to limit what we do, feel or think. Kellert (1983, 1986, 1991, 1993) therefore focused on examining the willingness of people of different nationalities and social groups to make personal sacrifices in favor of the environment and wildlife. It seems obvious that the most important factor influencing nature is not official environmental policy, but the public's willingness to care for the environment and bear the costs of minimizing the negative impacts of their activities (Ramsey Rickson, 1976).

# Bibliography

I didn't to much resources for the analysis section of this study. So, the work is mostly original. Some resources that helped me get started on this project and provide background information on the variables are as follows-

-   [LITERATURE REVIEW ON THE "CORRELATES OF THE PROENVIRONMENTAL BEHAVIOR"](http://hdl.handle.net/10263/7131) - A Dissertation by Dr. Arpita Chatterjee, under supervision of Dr. Debdulal Dutta Roy, Psychology Research Unit, Indian Statistical Institute dated January, 2021.

-   Questionnaire form has been made by [Dr. Debdulal Dutta Roy](https://www.isical.ac.in/~ddroy/), [Psychology Research Unit](https://pru.isical.ac.in/content/psychology-research-unit-0), [Indian Statistical Institute](https://www.isical.ac.in/).

# Tools & Code

The entire analysis was done in R, with the help of the freely available IDE, RStudio. This Report was written using RMarkdown.

The relevant code and the data used for this study and all necessary information are available at the GitHub Repository for this study [Pro-Environmental-Attitude-Analysis](https://github.com/RishiDarkDevil/Pro-Environmental-Attitude-Analysis).
